defmodule EscalimetroWeb.QRCode do
  @moduledoc """
  Small server-side QR renderer for invite URLs.

  It emits version 5-L QR codes in byte mode, which is enough for the short
  invite URLs generated by the application.
  """

  import Bitwise

  @size 37
  @data_codewords 108
  @ecc_codewords 26
  @max_bytes 106
  @quiet_zone 4

  def to_svg(data) when is_binary(data) do
    if byte_size(data) <= @max_bytes do
      data
      |> encode_codewords()
      |> build_matrix()
      |> render_svg(data)
    else
      fallback_svg(data)
    end
  end

  def to_svg(_data), do: fallback_svg("")

  defp encode_codewords(data) do
    data_codewords =
      data
      |> data_bits()
      |> pad_data_bits()
      |> bits_to_codewords()
      |> pad_codewords()

    data_codewords ++ reed_solomon_remainder(data_codewords, @ecc_codewords)
  end

  defp data_bits(data) do
    bytes = :binary.bin_to_list(data)

    [0, 1, 0, 0] ++ integer_bits(length(bytes), 8) ++ Enum.flat_map(bytes, &integer_bits(&1, 8))
  end

  defp pad_data_bits(bits) do
    capacity = @data_codewords * 8
    terminator_size = min(4, capacity - length(bits))
    bits = bits ++ List.duplicate(0, terminator_size)
    bits ++ List.duplicate(0, rem(8 - rem(length(bits), 8), 8))
  end

  defp bits_to_codewords(bits) do
    bits
    |> Enum.chunk_every(8)
    |> Enum.map(&bits_to_integer/1)
  end

  defp pad_codewords(codewords) do
    pad_bytes = Stream.cycle([0xEC, 0x11])

    codewords ++ Enum.take(pad_bytes, @data_codewords - length(codewords))
  end

  defp build_matrix(codewords) do
    {dark, reserved} =
      empty_matrix()
      |> draw_finder(0, 0)
      |> draw_finder(@size - 7, 0)
      |> draw_finder(0, @size - 7)
      |> draw_alignment(30, 30)
      |> draw_timing()
      |> reserve_format_areas()

    {dark, reserved}
    |> draw_data(codeword_bits(codewords))
    |> draw_format_bits()
  end

  defp empty_matrix, do: {MapSet.new(), MapSet.new()}

  defp draw_finder(matrix, left, top) do
    Enum.reduce(-1..7, matrix, fn dy, acc ->
      Enum.reduce(-1..7, acc, fn dx, matrix ->
        x = left + dx
        y = top + dy

        if in_bounds?(x, y) do
          dark? =
            dx in 0..6 and dy in 0..6 and
              (dx in [0, 6] or dy in [0, 6] or (dx in 2..4 and dy in 2..4))

          set_function(matrix, x, y, dark?)
        else
          matrix
        end
      end)
    end)
  end

  defp draw_alignment(matrix, center_x, center_y) do
    Enum.reduce(-2..2, matrix, fn dy, acc ->
      Enum.reduce(-2..2, acc, fn dx, matrix ->
        dark? = max(abs(dx), abs(dy)) == 2 or (dx == 0 and dy == 0)
        set_function(matrix, center_x + dx, center_y + dy, dark?)
      end)
    end)
  end

  defp draw_timing(matrix) do
    Enum.reduce(8..(@size - 9), matrix, fn i, matrix ->
      dark? = rem(i, 2) == 0

      matrix
      |> set_function(i, 6, dark?)
      |> set_function(6, i, dark?)
    end)
  end

  defp reserve_format_areas(matrix) do
    matrix =
      Enum.reduce(0..8, matrix, fn i, matrix ->
        if i == 6 do
          matrix
        else
          matrix
          |> set_function(8, i, false)
          |> set_function(i, 8, false)
        end
      end)

    matrix =
      Enum.reduce((@size - 8)..(@size - 1), matrix, fn i, matrix ->
        matrix
        |> set_function(8, i, false)
        |> set_function(i, 8, false)
      end)

    set_function(matrix, 8, @size - 8, true)
  end

  defp draw_data({dark, reserved}, bits) do
    {_index, dark} =
      data_coordinates()
      |> Enum.reduce({0, dark}, fn {x, y}, {index, dark} ->
        bit = Enum.at(bits, index, 0)
        dark? = bit == 1
        dark? = if mask?(x, y), do: not dark?, else: dark?

        dark =
          if dark? do
            MapSet.put(dark, {x, y})
          else
            MapSet.delete(dark, {x, y})
          end

        {index + 1, dark}
      end)

    {dark, reserved}
  end

  defp data_coordinates do
    {_dark, reserved} =
      empty_matrix()
      |> draw_finder(0, 0)
      |> draw_finder(@size - 7, 0)
      |> draw_finder(0, @size - 7)
      |> draw_alignment(30, 30)
      |> draw_timing()
      |> reserve_format_areas()

    collect_data_coordinates(@size - 1, :up, reserved, [])
  end

  defp collect_data_coordinates(right_x, _direction, _reserved, coordinates) when right_x <= 0,
    do: coordinates

  defp collect_data_coordinates(right_x, direction, reserved, coordinates) do
    right_x = if right_x == 6, do: 5, else: right_x

    rows =
      case direction do
        :up -> (@size - 1)..0//-1
        :down -> 0..(@size - 1)
      end

    next_coordinates =
      for y <- rows,
          x <- [right_x, right_x - 1],
          not MapSet.member?(reserved, {x, y}),
          do: {x, y}

    collect_data_coordinates(
      right_x - 2,
      opposite_direction(direction),
      reserved,
      coordinates ++ next_coordinates
    )
  end

  defp opposite_direction(:up), do: :down
  defp opposite_direction(:down), do: :up

  defp draw_format_bits({dark, reserved}) do
    format_bits = format_bits()

    {dark, reserved} =
      Enum.reduce(0..14, {dark, reserved}, fn i, matrix ->
        bit? = band(bsr(format_bits, i), 1) == 1

        matrix
        |> set_module(format_coordinate_a(i), bit?)
        |> set_module(format_coordinate_b(i), bit?)
      end)

    {dark, reserved}
  end

  defp format_bits do
    data = bsl(1, 3)

    remainder =
      Enum.reduce(0..9, data, fn _i, acc ->
        acc = bsl(acc, 1)

        if band(acc, 0x400) != 0 do
          bxor(acc, 0x537)
        else
          acc
        end
      end)

    bxor(bor(bsl(data, 10), band(remainder, 0x3FF)), 0x5412)
  end

  defp format_coordinate_a(i) when i <= 5, do: {8, i}
  defp format_coordinate_a(6), do: {8, 7}
  defp format_coordinate_a(7), do: {8, 8}
  defp format_coordinate_a(8), do: {7, 8}
  defp format_coordinate_a(i), do: {14 - i, 8}

  defp format_coordinate_b(i) when i <= 7, do: {@size - 1 - i, 8}
  defp format_coordinate_b(i), do: {8, @size - 15 + i}

  defp set_function({dark, reserved}, x, y, dark?) do
    set_module({dark, MapSet.put(reserved, {x, y})}, {x, y}, dark?)
  end

  defp set_module({dark, reserved}, {x, y}, dark?) do
    dark =
      if dark? do
        MapSet.put(dark, {x, y})
      else
        MapSet.delete(dark, {x, y})
      end

    {dark, reserved}
  end

  defp codeword_bits(codewords), do: Enum.flat_map(codewords, &integer_bits(&1, 8))

  defp integer_bits(value, count) do
    for shift <- (count - 1)..0//-1, do: band(bsr(value, shift), 1)
  end

  defp bits_to_integer(bits) do
    Enum.reduce(bits, 0, fn bit, acc -> bor(bsl(acc, 1), bit) end)
  end

  defp reed_solomon_remainder(data, degree) do
    generator = reed_solomon_generator(degree)

    Enum.reduce(data, List.duplicate(0, degree), fn byte, remainder ->
      factor = bxor(byte, hd(remainder))
      shifted = tl(remainder) ++ [0]

      shifted
      |> Enum.zip(tl(generator))
      |> Enum.map(fn {coefficient, generator_coefficient} ->
        bxor(coefficient, gf_multiply(generator_coefficient, factor))
      end)
    end)
  end

  defp reed_solomon_generator(degree) do
    Enum.reduce(0..(degree - 1), [1], fn exponent, generator ->
      polynomial_multiply(generator, [1, gf_power(2, exponent)])
    end)
  end

  defp polynomial_multiply(left, right) do
    coefficients = List.duplicate(0, length(left) + length(right) - 1)

    left
    |> Enum.with_index()
    |> Enum.reduce(coefficients, fn {left_coefficient, left_index}, coefficients ->
      right
      |> Enum.with_index()
      |> Enum.reduce(coefficients, fn {right_coefficient, right_index}, coefficients ->
        index = left_index + right_index

        value =
          bxor(Enum.at(coefficients, index), gf_multiply(left_coefficient, right_coefficient))

        List.replace_at(coefficients, index, value)
      end)
    end)
  end

  defp gf_power(_value, 0), do: 1

  defp gf_power(value, power) do
    Enum.reduce(1..power, 1, fn _i, acc -> gf_multiply(acc, value) end)
  end

  defp gf_multiply(left, right) do
    {product, _left, _right} =
      Enum.reduce(0..7, {0, left, right}, fn _i, {product, left, right} ->
        product = if band(right, 1) == 1, do: bxor(product, left), else: product

        left =
          if band(left, 0x80) == 0x80 do
            bxor(bsl(left, 1), 0x11D)
          else
            bsl(left, 1)
          end

        {product, band(left, 0xFF), bsr(right, 1)}
      end)

    product
  end

  defp mask?(x, y), do: rem(x + y, 2) == 0

  defp in_bounds?(x, y), do: x >= 0 and x < @size and y >= 0 and y < @size

  defp render_svg({dark, _reserved}, data) do
    viewbox_size = @size + @quiet_zone * 2

    modules =
      dark
      |> Enum.sort_by(fn {x, y} -> {y, x} end)
      |> Enum.map_join("", fn {x, y} ->
        ~s(<rect x="#{x + @quiet_zone}" y="#{y + @quiet_zone}" width="1" height="1"/>)
      end)

    ~s(<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="QRCode do convite" viewBox="0 0 #{viewbox_size} #{viewbox_size}" shape-rendering="crispEdges" data-url="#{escape_attr(data)}"><rect width="100%" height="100%" fill="white"/><g fill="black">#{modules}</g></svg>)
  end

  defp fallback_svg(data) do
    ~s(<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="QRCode indisponivel" viewBox="0 0 45 45" data-url="#{escape_attr(data)}"><rect width="45" height="45" fill="white"/><path d="M4 4h12v12H4zM29 4h12v12H29zM4 29h12v12H4z" fill="black"/><path d="M20 20h5v5h-5zM28 24h4v4h-4zM22 31h11v3H22z" fill="black"/></svg>)
  end

  defp escape_attr(value) do
    value
    |> String.replace("&", "&amp;")
    |> String.replace("\"", "&quot;")
    |> String.replace("<", "&lt;")
    |> String.replace(">", "&gt;")
  end
end
